### ISSUE TITLE
Bug: AltimateRefArgs fails with validation error when dbt macros are documented with arguments type and description

### ISSUE THREAD

**Issue by bf-samspar** [AltimateAI/datapilot-cli#30]
When running ```datapilot dbt project-health``` on my dbt project I get the attached error. It seems like the class AltimateRefArgs("https://github.com/AltimateAI/datapilot-cli/blob/main/src/datapilot/core/platforms/dbt/schemas/manifest.py") don't accept the fields "description" and "type". These fields are typically used when documenting macro arguments in dbt, https://docs.getdbt.com/faqs/Docs/documenting-macros.

Error:
```
pydantic.error_wrappers.ValidationError: 2 validation errors for AltimateRefArgs
description
  extra fields not permitted (type=value_error.extra)
type
  extra fields not permitted (type=value_error.extra)
```

**Comment by anandgupta42** [comment]
fixed in #32
